export const DEPARTMENTS = [
  '콘텐츠 개발실',
  '대외협력실',
  '전략기획실',
  '경영지원실',
  '후원성장지원팀',
  '뉴브랜드'
] as const;

export const TEXTS = {
  COMMON: {
    APP_NAME: "복음의전함",
    APP_SUBTITLE: "업무요청 및 관리 시스템",
    SEARCH_PLACEHOLDER: "요청 검색...",
    LOGOUT: "로그아웃",
    SETTINGS: "설정",
    CANCEL: "취소",
    SUBMIT: "제출하기",
    SAVE: "저장",
    DELETE: "삭제",
    EDIT: "수정",
    ADMIN: "관리자",
    MANAGER: "부서담당자",
    STAFF: "업무담당자",
    FINANCE: "재정담당",
    STATUS: "상태",
    PRIORITY: "우선순위",
    DUE_DATE: "기한",
    CREATED_AT: "생성일",
    DEPARTMENT: "부서",
    TARGET_DEPARTMENT: "담당 부서",
    REQUESTER: "요청자",
    PROJECT_NAME: "프로젝트명",
    DESCRIPTION: "상세 내용",
    ATTACHMENTS: "첨부 파일",
    COMMENTS: "의견 및 협업",
    HISTORY: "진행 이력",
    ALL: "전체",
    HISTORY_CREATED: "요청 생성됨",
    HISTORY_STATUS_CHANGED: "상태 변경",
  },
  SIDEBAR: {
    DASHBOARD: "대시보드",
    MY_REQUESTS: "업무 현황",
    CREATE_REQUEST: "요청 생성",
    ADMIN: "관리자",
    NEW_REQUEST_BTN: "신규 요청",
    SETTINGS: "설정",
    LOGOUT: "로그아웃",
  },
  DASHBOARD: {
    TITLE: "업무 통합 관제 센터",
    SUBTITLE: "복음의전함 업무 요청 및 관리 시스템 운영 개요입니다.",
    SYSTEM_STATUS: "시스템 상태: 최적",
    STATS: {
      TOTAL: "전체 업무 요청",
      IN_PROGRESS: "진행 중인 업무",
      PENDING: "검토 대기",
      COMPLETED: "업무 완료",
    },
    RECENT_TASKS: "최근 업무 요청",
    VIEW_ALL: "전체 보기",
    DEPT_STATUS: "팀별 업무 현황",
    EFFICIENCY_TITLE: "업무 처리 효율성",
    EFFICIENCY_DESC: "미디어선교팀의 워크플로우가 지난 분기 대비 14% 향상되었습니다. 온라인 복음광고 캠페인 처리가 가속화되고 있습니다.",
    METRICS: {
      PROGRESS: "업무 진행률",
      MONTHLY_COUNT: "이번 달 접수",
      AVG_DAYS: "평균 소요일",
      REJECTION_RATE: "반려율",
    },
    SECURITY_TITLE: "보안 및 컴플라이언스",
    SECURITY_DESC: "모든 업무 데이터는 교단 및 사단법인 데이터 정책을 준수하여 안전하게 관리되고 있습니다.",
  },
  REQUEST_LIST: {
    TITLE: "업무 현황",
    SUBTITLE: "팀 간 업무 협력 흐름을 관리하고 추적합니다.",
    EXPORT_EXCEL: "엑셀 내보내기",
    NEW_REQUEST: "신규 업무 요청",
    FILTER_STATUS: "상태 필터",
    FILTER_PERIOD: "기간 필터",
    TOTAL_COUNT: "총 {count}건",
    TABLE: {
      ID: "요청 번호",
      TITLE: "제목",
      DEPT: "요청 팀",
      TARGET_DEPT: "담당 팀",
      ASSIGNEE: "담당자",
      LAST_UPDATED: "최근 변경일",
    },
  },
  CREATE_REQUEST: {
    TITLE: "신규 업무 요청",
    SUBTITLE: "업무 프로젝트를 적절한 팀 및 우선순위 대기열로 배정하기 위해 상세 내용을 작성해 주세요.",
    FIELD_TITLE: "업무 요청 제목",
    FIELD_TITLE_PLACEHOLDER: "업무 내용을 명확히 알 수 있는 제목을 입력하세요...",
    FIELD_DESC: "업무 상세 내용",
    FIELD_DESC_PLACEHOLDER: "업무의 목적, 요구 사항, 배경 정보를 상세히 입력해 주세요...",
    FIELD_DUE_DATE: "업무 완료 희망일",
    FIELD_PRIORITY: "긴급도",
    UPLOAD_TITLE: "업무 관련 에셋 첨부",
    UPLOAD_DESC: "기획안, 디자인 가이드, 참고 자료를 여기에 끌어다 놓으세요.",
    BROWSE_FILES: "파일 찾아보기",
    SUBMIT_BTN: "업무 요청 제출",
    SECURITY_NOTICE: "모든 업무 요청은 내부 규정에 따라 기록되며 투명하게 관리됩니다.",
  },
  REQUEST_DETAIL: {
    ID_LABEL: "업무 ID",
    STATUS_CHANGE: "상태 변경",
    SUMMARY: "업무 요약",
    HISTORY_TITLE: "업무 진행 이력",
    STAKEHOLDERS: "업무 관계자",
    ASSIGNEE: "업무 담당자",
    REVIEWER: "검토자",
    COPY_BTN: "요청 복사",
    COMMENT_PLACEHOLDER: "의견을 남기거나 동료를 태그하세요...",
    NOT_FOUND: "요청을 찾을 수 없습니다.",
    BACK_TO_LIST: "목록으로 돌아가기",
    REJECT_BTN: "반려",
    APPROVE_BTN: "승인",
    REVIEW_BTN: "검토 시작",
    START_BTN: "진행중으로 변경",
    COMPLETE_BTN: "업무 완료 처리",
    RESUBMIT_BTN: "재제출",
    MODAL: {
      TITLE: "상태 변경 확인",
      COMMENT_LABEL: "변경 사유 또는 메모 (선택)",
      CONFIRM: "확인",
      CANCEL: "취소",
    },
    HISTORY: {
      TITLE: "상태 변경 이력 타임라인",
      EMPTY: "변경 이력이 없습니다.",
      FROM: "이전",
      TO: "이후",
      COMMENT: "메모",
    },
    LABEL_DESC: "상세 내용",
    LABEL_ATTACHMENTS: "첨부 파일",
    LABEL_COMMENTS: "의견 및 협업",
    LABEL_REQUESTER: "요청자",
    LABEL_DEPT: "요청 부서",
    LABEL_TARGET_DEPT: "담당 부서",
    LABEL_DUE_DATE: "기한",
    LABEL_ASSIGNEE: "담당자",
    ASSIGN_BTN: "담당자 지정/변경",
    UNASSIGNED: "미지정",
  },
  ADMIN: {
    TITLE: "업무담당자 관리",
    SUBTITLE: "업무담당자, 팀장 및 관리자의 통합 디렉토리입니다. 시스템 접근 권한을 관리합니다.",
    ADD_USER: "신규 업무담당자 등록",
    STATS_TOTAL_USERS: "전체 업무담당자",
    STATS_ADMINS: "관리자 수",
    STATS_PENDING: "대기 중인 요청",
    STATS_REJECTED: "반려된 요청",
    USER_MANAGEMENT: "사용자 계정 관리",
    SEARCH_PLACEHOLDER: "이름, 사번 또는 팀으로 검색...",
    TABLE_NAME: "이름",
    TABLE_ROLE: "권한",
    TABLE_DEPT: "소속 팀",
    TABLE_STATUS: "상태",
    TABLE_ACTIONS: "관리",
    STATUS_ACTIVE: "활성",
    SECURITY_NOTICE_TITLE: "보안 및 계정 정책",
    SECURITY_NOTICE_DESC: "모든 계정 활동은 감사 로그에 기록됩니다. 권한 변경 시 반드시 내부 승인 절차를 준수해 주세요.",
  },
  DEPARTMENTS: {
    CONTENT: "콘텐츠 개발실",
    PARTNERSHIP: "대외협력실",
    PLANNING: "전략기획실",
    SUPPORT: "경영지원실",
    GROWTH: "후원성장지원팀",
    NEWBRAND: "뉴브랜드",
  },
  PRIORITIES: {
    LOW: "낮음",
    MEDIUM: "중간",
    HIGH: "높음",
    URGENT: "긴급",
  },
  STATUSES: {
    DRAFT: "작성중",
    SUBMITTED: "제출",
    REVIEWING: "검토중",
    REJECTED: "반려",
    APPROVED: "승인",
    IN_PROGRESS: "진행중",
    COMPLETED: "완료",
    ON_HOLD: "보류",
  },
  ROLES: {
    ADMIN: "관리자",
    MANAGER: "부서담당자",
    USER: "업무담당자",
    FINANCE: "재정담당",
  },
};
